const DataController = require("../controllers/data.controller");
const express = require("express");
const router = express.Router();
router.get("/intensity", DataController.prototype.Intensity);
router.get("/likelihood", DataController.prototype.Likelihood);
router.get("/relevance", DataController.prototype.Relevance);
router.get("/year/:start_year/:end_year", DataController.prototype.Year);
router.get("/countryList", DataController.prototype.CountryList);
router.get("/country/:country", DataController.prototype.Countries);
router.get("/topicList", DataController.prototype.TopicList);
router.get("/topic/:topic", DataController.prototype.Topics);
router.get("/regionList", DataController.prototype.RegionList);
router.get("/region/:region", DataController.prototype.Regions);
module.exports = router;
